### ISSUE TITLE
source("firstscript.R")

### ISSUE THREAD

**Issue by grantcramer** [ClaudiaBrauer/A-very-short-introduction-to-R#4]
When I followed the instructions by creating a new folder called "swirl" in my directory and typed in this command I got:

Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file 'firstscript.R': No such file or directory

I recreated another file in the directory and repeated the command and got the same message.

I don't know what the problem is but it would be useful for my students to know what the swirl command is to bypass this issue.

**Comment by ClaudiaBrauer** [comment]
Dear Grant,

Thanks for using the swirl module!

Is it possible that the working directory is not set to the folder where the file is? You can find out what the working directory is with getwd() and, if necessary, set it to the right path with setwd(“...”), where you replace ... with the correct path of course.

I hope this helps!
Claudia

________________________________
C.C. Brauer, PhD., lecturer-researcher
Hydrology and Quantitative Water Management Group, Wageningen University

**Comment by grantcramer** [comment]
No, it was correct. the first and third module worked fine.
Grant R. Cramer
Professor
Department of Biochemistry and Molecular Biology, Howard Building Room 205, Mail Stop 330
University of Nevada, Reno
Reno, NV 89557
(775) 784-4204
cramer@unr.edu<mailto:cramer@unr.edu>
http://www.ag.unr.edu/cramer/

On Feb 21, 2019, at 5:57 AM, Claudia Brauer <notifications@github.com<mailto:notifications@github.com>> wrote:

Dear Grant,

Thanks for using the swirl module!

Is it possible that the working directory is not set to the folder where the file is? You can find out what the working directory is with getwd() and, if necessary, set it to the right path with setwd(“...”), where you replace ... with the correct path of course.

I hope this helps!
Claudia

________________________________
C.C. Brauer, PhD., lecturer-researcher
Hydrology and Quantitative Water Management Group, Wageningen University

**Comment by ClaudiaBrauer** [comment]
Dear Grant,


I finally found time to look at the error and I think I managed to fix it. The problem was that when swirl does not expect a response (when you see "..." instead of ">"), everything you click or type is ignored. So I changed that.


I attached a new version of the swc file to this email and also uploaded a new version on my own github site. It will hopefully be updated on the Swirl Course Network site soon too, so you can download the new version automatically.


Thanks for pointing out the error! I hope the course was/is useful for you and your students.


Good luck!

Claudia


________________________________
C.C. Brauer, PhD., lecturer-researcher
Hydrology and Quantitative Water Management Group, Wageningen University and Research

________________________________
Van: grantcramer <notifications@github.com>
Verzonden: donderdag 21 februari 2019 21:54
Aan: ClaudiaBrauer/A-very-short-introduction-to-R
CC: Brauer, Claudia; Comment
Onderwerp: Re: [ClaudiaBrauer/A-very-short-introduction-to-R] source("firstscript.R") (#4)

No, it was correct. the first and third module worked fine.
Grant R. Cramer
Professor
Department of Biochemistry and Molecular Biology, Howard Building Room 205, Mail Stop 330
University of Nevada, Reno
Reno, NV 89557
(775) 784-4204
cramer@unr.edu<mailto:cramer@unr.edu>
http://www.ag.unr.edu/cramer/

On Feb 21, 2019, at 5:57 AM, Claudia Brauer <notifications@github.com<mailto:notifications@github.com>> wrote:

Dear Grant,

Thanks for using the swirl module!

Is it possible that the working directory is not set to the folder where the file is? You can find out what the working directory is with getwd() and, if necessary, set it to the right path with setwd(“...”), where you replace ... with the correct path of course.

I hope this helps!
Claudia

________________________________
C.C. Brauer, PhD., lecturer-researcher
Hydrology and Quantitative Water Management Group, Wageningen University

**Comment by ClaudiaBrauer** [comment]
Dear Grant,

I finally found time to look at the error and I think I managed to fix it. The problem was that when swirl does not expect a response (when you see "..." instead of ">"), everything you click or type is ignored. So I changed that. 

I uploaded a new version of the swc file to this github site. It will hopefully be updated on the Swirl Course Network site soon too, so you can download the new version automatically in R.  

Thanks for pointing out the error! I hope the course was/is useful for you and your students. 

Good luck!
Claudia

**Comment by grantcramer** [comment]
Yes, it was, and I am glad I contributed to finding an error! Thanks for letting my know!
All the best,
Grant

Grant R. Cramer
Professor
Department of Biochemistry and Molecular Biology, Howard Building Room 205, Mail Stop 330
University of Nevada, Reno
Reno, NV 89557
(775) 784-4204
cramer@unr.edu<mailto:cramer@unr.edu>
http://www.ag.unr.edu/cramer/

On Apr 2, 2019, at 7:46 AM, Claudia Brauer <notifications@github.com<mailto:notifications@github.com>> wrote:

Dear Grant,


I finally found time to look at the error and I think I managed to fix it. The problem was that when swirl does not expect a response (when you see "..." instead of ">"), everything you click or type is ignored. So I changed that.


I attached a new version of the swc file to this email and also uploaded a new version on my own github site. It will hopefully be updated on the Swirl Course Network site soon too, so you can download the new version automatically.


Thanks for pointing out the error! I hope the course was/is useful for you and your students.


Good luck!

Claudia


________________________________
C.C. Brauer, PhD., lecturer-researcher
Hydrology and Quantitative Water Management Group, Wageningen University and Research

________________________________
Van: grantcramer <notifications@github.com<mailto:notifications@github.com>>
Verzonden: donderdag 21 februari 2019 21:54
Aan: ClaudiaBrauer/A-very-short-introduction-to-R
CC: Brauer, Claudia; Comment
Onderwerp: Re: [ClaudiaBrauer/A-very-short-introduction-to-R] source("firstscript.R") (#4)

No, it was correct. the first and third module worked fine.
Grant R. Cramer
Professor
Department of Biochemistry and Molecular Biology, Howard Building Room 205, Mail Stop 330
University of Nevada, Reno
Reno, NV 89557
(775) 784-4204
cramer@unr.edu<mailto:cramer@unr.edu><mailto:cramer@unr.edu>
http://www.ag.unr.edu/cramer/

On Feb 21, 2019, at 5:57 AM, Claudia Brauer <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:

Dear Grant,

Thanks for using the swirl module!

Is it possible that the working directory is not set to the folder where the file is? You can find out what the working directory is with getwd() and, if necessary, set it to the right path with setwd(“...”), where you replace ... with the correct path of course.

I hope this helps!
Claudia

________________________________
C.C. Brauer, PhD., lecturer-researcher
Hydrology and Quantitative Water Management Group, Wageningen University

**Comment by ClaudiaBrauer** [comment]
The version on the Swirl Course Network site has been updated as well, so you can install the newest version directly through install_course("A_(very)_short_introduction_to_R").
